### ISSUE TITLE
"_embedded" (single) resource object not supported?

### ISSUE THREAD

**Issue by marceloverdijk** [otto-de/edison-hal#21]
Is it correct - when rendering HalRepresentation - that is not supported to have a single resource object in `_embedded`?

As per the spec:

> The reserved "_embedded" property is OPTIONAL
>
>   It is an object whose property names are link relation types (as
>   defined by [RFC5988]) and values are either a Resource Object or an
>   array of Resource Objects.

edison-hal seems to only allow to set a list of resources in the `_embedded` property like:

`protected HalRepresentation withEmbedded(final String rel, final List<? extends HalRepresentation> embeddedItems)`

In some cases an explicit single resource is desired instead of an array.

**Comment by gsteinacker** [comment]
This is indeed not yet supported. Fixing this will take some time as I am currently working on a different topic. It would be great if you could contribute a fix for this...

**Comment by marceloverdijk** [comment]
Yes, the problem here is to both support single and array of embedded items.
I do think this is an important feature as without clients need to take `[0]` even if it's always a single embedded resource.

**Comment by gsteinacker** [comment]
Currently, there is a "RelRegistry" which has a feature ('arrayRels') used to render Links as an array of links, even if there is only a single link for a link relation type. For example, 'curies' are always rendered as an array, even if there is only a single CURI link (because it's specified like this).

I am not happy with this feature of RelRegistry, because - well - it's rather ugly...

The same feature could be used to configure single-valued _embedded resources. However, it might be more explicit to use methods like:
- Links#linkingTo(Link) -> render the link as a single link
- Links#linkingTo(List<Link>) -> render the links as an array of links - even if the Link is only containing a single item
- Embedded#embedded(String rel, HalRepresentation embedded) -> render the link as a single embedded resource
- Embedded#embedded(String rel, List<? extends HalRepresentation> embedded) -> render the link as an array of embedded resources - even if there is only a single resource in the list

Doing so would make it inconclusive to have a method like Links#linkingTo(Link, Link...), so I would have to remove it (or replace it by something like Links#linkingTo(Link first, Link second, Link... more)).  

However, there is a minor downside of using the signatures of linkingTo() or embedded() to distinguish between single resource or arrays of (links, embedded) things: it could easily become inconsistent for link-relation types. Sometimes an 'author' may become an object, sometimes an array of author-objects - depending on the method-signature you are using. 

Would it be better to have separate - explicit - methods like Links#linkingToSingle(Link) / Links#linkingToArrayOf(List<Link>) and Embedded#embeddedSingle(String,  HalRepresentation) / Embedded#embeddedArrayOf(String, List<? extends HalRepresentation)? This would break a lot of existing code (at OTTO) but might help to understand what's happening...

What do you think?

**Comment by marceloverdijk** [comment]
I think I would prefer the `Embedded#embedded(String rel, HalRepresentation embedded)` and `Embedded#embedded(String rel, List<? extends HalRepresentation> embedded)` variants.
It is more readable friendly compared to `embeddedSingle` and `embeddedArrayOf`.

**Comment by gsteinacker** [comment]
I have just uploaded another SNAPSHOT that might fix your issues. It is now possible to specify, which Links and Embedded objects will become single link-objects, or single embedded objects using the Links.Builder and/or Embedded classes. 
Because of this, the creation of links has been changed; please have a look at the README for examples.
