### ISSUE TITLE
remove duplicate curis from embedded resources

### ISSUE THREAD

**Issue by Danny02** [otto-de/edison-hal#22]
Hi,

I have an idea for improvment and I would like to know what you think.

I have multiple HalRepresentation which have rels which use curis. Representation A would like to embed representation B, both use rels which can use the same curi.

My HAL representation factory of B always includes a curi link. When I now serialize an Repr. A, the curi will be duplicated in the JSON.

At the moment embedded representations use the relRegistry of the parent, it would be nice to remove duplicated curis at the same time.

**Comment by gsteinacker** [comment]
Hi Daniel,
thanks for your proposal! As far as I understand, your document currently becomes something like:
```
{
"_links": {
   "curies": [{"name":"x", "href":"http://example.com/rels/{rel}","templated":true}]
},
"_embedded": {
   "_links": {
      "curies": [{"name":"x", "href":"http://example.com/rels/{rel}","templated":true}]
   },
   "description": "This is object B"
},
   "description": "This is object A"
}
```
...which is indeed not too pretty. If I remember it right, the purpose of HalRepresentation#mergeWithEmbedding(Curies) is what you are looking for - but maybe it is not working properly or it is not called in your use case.

Would you mind to provide a test that is producing the bug? If you have some time, feel also free to contribute to the project with a fix :-) Otherwise you will have to wait a few days.

BTW: You are probably using version 1.0.0? The current SNAPSHOT of version 2 needs some feedback (+ tests), too...

Thanks again, Guido

**Comment by gsteinacker** [comment]
äh - please ignore the illegal structure in the above example...

**Comment by Danny02** [comment]
I think you would have to modify this [constructor](https://github.com/otto-de/edison-hal/blob/master/src/main/java/de/otto/edison/hal/Links.java#L84) and remove curi links which are already present in the RelRegistry/Curies.
