### ISSUE TITLE
Allow customization of the Jackson ObjectMapper used in HalParser

### ISSUE THREAD

**Issue by joaocabrita** [otto-de/edison-hal#23]
Without this, it's impossible to add modules to make client-side deserialization match the server-side serialization configuration.

**Comment by guidosteinacker1969** [comment]
Hi,
thank you for the bug report. If fixed this by adding methods for HalParser.parse() and Traversen.traverson() that accept an optional ObjectMapper instance. Please have a look...

Because it was already overdue, I also released 2.0.0; it should be available at Maven Central in a few hours.

Have fun - and please come back to me, if you have any more issues.

-- 
Guido

**Comment by guidosteinacker1969** [comment]
Thank you for the hint - and sorry for the delay. I have fixed it now, at least for the current 2.0.1 RELEASE. 

-- 
Guido
